version: '2'
networks:
  default:
    external:
      name: external-example

services:
  discovery-server:
    image: 'discovery-server:latest'
    build:
      context: .
    container_name: discovery-server
    ports:
      - 8761:8761
